name = "or_error"
version = "1.0.0"

description = "A pragmatic approach to error handling in gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "jmilik", repo = "or_error" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
